### PR TITLE
Abstract fixed.

### PR DESCRIPTION
**Pull request by shinnkj23**
The abstract was wrong (it was of another paper.).  I copied the correct one.

### CODE REVIEW

**Comment by lawrennd** [comment]
Thanks for the fix!

**Comment by shinnkj23** [comment]
Thank you for taking care of the proceedings!

Best,
Shin

**Comment by shinnkj23** [comment]
Dear Neil,

Sorry to bother you again.
It seems that the paper of which I fixed the abstract (the md file) 
disappeared

http://proceedings.mlr.press/v101/
(It should be the paper in pages 173-187)

Did I modify a wrong file?

Best,
Shin

**Comment by lawrennd** [comment]
I think the breaking of the abstract across the lines confused the yaml header, I've had a go at fixing it. It seems to be back in place for me now.

**Comment by shinnkj23** [comment]
Great thanks!

Best,
Shin

**Pull request merged**
