### PR TITLE
Update 2019-10-15-konagayoshi19a.md

### PR DESCRIPTION
**Pull request by shinnkj23**
Another fix.  Could you please merge it?

### CODE REVIEW

**Comment by lawrennd** [comment]
Sure, could you jyst add details of the change and why it’s needed before merge? Just so we have the record of it. Thanks!

**Comment by shinnkj23** [comment]
Sorry I forgot to mention.  The abstract of the paper /v101/konagayoshi19a was wrong (came from another paper).  I fixed it to the correct one.

**Comment by shinnkj23** [comment]
Dear Neil,

I added a comment explaining the change.
Could you please merge it?

Best,
Shin

**Comment by shinnkj23** [comment]
Dear Neil,

Could you please merge the change?  Or shall I need to do something more?

Best,
Shin

**Comment by shinnkj23** [comment]
Thanks!

Best,
Shin

**Pull request merged**
